databases:
     - name: snap_and_eat_postgres
       databaseName: snap_and_eat
       user: snap_and_eat

   services:
     - type: web
       name: snap_and_eat
       env: ruby
       buildCommand: "./bin/render-build.sh"
       startCommand: "bundle exec puma -C config/puma.rb"
       envVars:
         - key: DATABASE_URL
           fromDatabase:
             name: snap_and_eat_postgres
             property: connectionString
         - key: RAILS_MASTER_KEY
           sync: false